# This is a basic workflow to help you get started with Actions

name: invoke action

# Controls when the workflow will run
on:  
  workflow_dispatch :
      branches: [ main ]

  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install

      # Runs a single command using the runners shell
      - uses: amitgupta7/ghas-reports-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: alerts.xlsx
